stack = [3, 4, 5]
stack.append(6)
stack.append(7)
print(stack)
print("=="*10)
print(stack.pop())
print("=="*10)
print(stack)
print("=="*10)
print(stack.pop())
print("=="*10)
print(stack.pop())
print("=="*10)
print(stack)